//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesAPiClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string username { get; set; }
        public byte[] key { get; set; }
        public byte[] salt { get; set; }

        public user(int id, string username, byte[] key, byte[] salt)
        {
            this.id = id;
            this.username = username;
            this.key = key;
            this.salt = salt;
        }

        public user()
        {
        }

        public user(string username, byte[] key, byte[] salt)
        {
            this.username = username;
            this.key = key;
            this.salt = salt;
        }
    }
}
